### ISSUE TITLE
Hactoberfest Projects Contributions

### ISSUE THREAD

**Issue by WebDevSAAS** [WebDevSAAS/OS-Projects#1]
Please add only JS projects only. And do contributions on given issues only. Your PR will be merged only if you follow Hacktober-Fest guidelines.

**Comment by Sagun-png** [comment]
Hey @WebDevSAAS , I would love to contribute my JS project. Please do assign me this.

**Comment by Sagun-png** [comment]
I sent my PR. Assign me this work.
